### ISSUE TITLE
Video Chat on Android. Disable embedded buttons.

### ISSUE THREAD

**Issue by JavierTous** [cometchat-pro-samples/android-java-chat-app#11]
Need to be able to set actions (maybe overriding interface) or just disable the embedded buttons on the VideoChat. Specifically the add caller and menu button. These buttons as of now can't be disabled.

**Comment by adityagokula2210** [comment]
@JavierTous 
At the moment there is no option to modify the video component. We are working on making the video chat component more flexible. Since its a major architectural change we cannot promise a definite timeline for the same. We are hoping to get this done in a couple of weeks and will definitely let you know once the changes are live.
Thanks.

**Comment by anantgarg** [comment]
@JavierTous please upvote this request: https://feedback.cometchat.com/admin/board/cometchat-pro/p/custom-video-ui

Then you'll receive a notification once this feature is released.

**Comment by darshanbhanushali** [comment]
Hi,

We have updated our sample app with the latest SDK v2.1.0 which has a completely new Calling module in place. Please upgrade to the latest version and provide us with your feedback.
Also, check the latest docs which include implementation details for a new calling module.
https://prodocs.cometchat.com/docs/android-calling
